CREATE DATABASE IF NOT EXISTS all_decrypt
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE all_decrypt;


CREATE TABLE IF NOT EXISTS contents
(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,

    label VARCHAR(255) NOT NULL,

    image VARCHAR(500) NOT NULL,

    status TINYINT(1) NOT NULL DEFAULT 1,

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)

)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;
